BLADESLINGER_ATT_INTERVAL = 0.2

PACE_OF_STORM_RADIUS = 700
PACE_OF_STORM_COOLDOWN = 1
PACE_OF_STORM_MIN_AMP = 0.4
PACE_OF_STORM_MAX_AMP = 4
PACE_OF_STORM_STEADFAST_THRESHOLD = 10
PACE_OF_STORM_MEGASTEADFAST_THRESHOLD = 30

SANGE_HP_PER_AGI = 25
SANGE_MP_PER_AGI = 5

PEGASUS_MAX_MS_AMP_PCT = 30
PEGASUS_E_SPEED_PCT = 100

PIVOT_BOOT_MAX_MS = 850
PIVOT_BOOT_MS = 400
PIVOT_BURST_DURATION = 4