BARON_STORM_MAX_TARGETS = 6
BARON_STORM_DMG_RESISTANCE = 0.85
BARON_STORM_DMG_PER_ATT = 5
BARON_STORM_DUR = 5
BARON_STORM_COOLDOWN = 0.1
BARON_STORM_SEARCH_RADIUS = 500

HURRICANE_VEST_MAX_DISTANCE = 1800
HURRICANE_VEST_DMG_AMP = 10
HURRICANE_VEST_DMG_EXP_SCALE = 3
HURRICANE_VEST_MSP_REDUCE = 150
HURRICANE_VEST_ATT_SPD_REDUCE = 150
HURRICANE_VEST_SLOW_DUR = 5
HURRICANE_VEST_HURRICANE_SPEED = 1000
HURRICANE_VEST_HURRICANE_COUNT = 16

TEMPLAR_LIGHT_SEER_MAX_STACKS = 20

ERUDITE_TEACHER_HEALTH_MULT = 5
ERUDITE_TEACHER_ATTACK_MULT = 10
ERUDITE_TEACHER_ARMOR_MULT = 10

ALIEN_ARMOR_OUTGOING_DAMAGE_MULT = 500
ALIEN_ARMOR_INCOMING_DAMAGE_REDUCTION = 90
ALIEN_ARMOR_ILLUSION_DURATION = 10
ALIEN_ARMOR_ILLUSION_AS = 1000
ALIEN_ARMOR_RESPAWN_DELAY = 3

NETHERGRASP_MAX_LINKS = 5
NETHERGRASP_BREAK_DISTANCE = 1600
NETHERGRASP_LINK_RANGE = 1200
NETHERGRASP_ATTACK_INTERVAL = 0.15