BLUE_RAIN_CHANCE = 15
BLUE_RAIN_DMG_PER_ATT = 75

ELDER_GRASP_HEAL_PCT = 0.1
ELDER_GRASP_RADIUS = 500
ELDER_GRASP_SHIELD_PER_HP = 3

GRAVEKEEPER_MAX_STACKS_PER_SEC = 8

STORMCLOTH_COOLDOWN = 6
STORMCLOTH_STUN_DUR = 1.5
STORMCLOTH_STUN_AOE = 900

CHITINOUS_LOBSTER_CLAW_DMG_RED_PER_STACK = 0.01
CHITINOUS_LOBSTER_CLAW_MAX_STACKS = 92
CHITINOUS_LOBSTER_CLAW_STACK_RATE = 0.2

CYTOPIAN_LASER_DMG_PER_ATT = 3
CYTOPIAN_LASER_MAX_STACKS = 10
CYTOPIAN_LASER_RADIUS = 750

HALCYON_SOUL_GLOVE_BONUS = 0.5

GOLDBREAKER_DEBUFF_DURATION = 7

GAUNTLET_OF_DIVINE_PURITY_MULTIPLIER = 20