BASILISK_PLAGUE_PHYSICAL_POSTMIT = 15
BASILISK_PLAGUE_MOVESPEED_REDUCE_PCT = 50
BASILISK_PLAGUE_ATT_SPD_REDUCE = 240
BASILISK_PLAGUE_TIME_BEFORE_STONE_FORM = 2
BASILISK_PLAGUE_THINK_INTERVAL = 0.5
BASILISK_PLAGUE_STONE_FORM_DUR = 2

KABUTO_SHIELD_DUR = 4
KABUTO_SHIELD_RESISTANCE = 0.95

LAVA_FORGE_DMG_PER_ATT = 2
LAVA_FORGE_DMG_PER_AGI = 2000
LAVA_FORGE_RADIUS = 240

SHIPYARD_SHIELD_COOLDOWN = 0.1

IRON_COLOSSUS_ATT_PER_STR = 10
IRON_COLOSSUS_AMR_PER_STR = 0.5
IRON_COLOSSUS_DMG_PER_ATT = 50
IRON_COLOSSUS_ATT_SPD = 120
IRON_COLOSSUS_ATT_RNG = 180

RUBY_DRAGON_TICK_INTERVAL = 0.2
RUBY_DRAGON_TICK_DURATION = 9
RUBY_DRAGON_TICK_DMG_PER_STR = 1500
RUBY_DRAGON_IMPACT_DMG_PER_STR = 5000
RUBY_DRAGON_DURATION = 15
RUBY_DRAGON_DISTANCE = 1300

SUPER_ASCENDENCY_ATK_RANGE = 800
SUPER_ASCENDENCY_ATK_PCT = 150
SUPER_ASCENDENCY_ATK_SPD = 300
SUPER_ASCENDENCY_MOVE_SPD = 200
SUPER_ASCENDENCY_PROJECTILE_SPEED = 500
SUPER_ASCENDENCY_SEARCH_RADIUS = 550
SUPER_ASCENDENCY_CD_RED = 0.05
SUPER_ASCENDENCY_TARGETS = 5
SUPER_ASCENDENCY_MIN_DURATION = 12

STORMCRACK_ATTACK_DAMAGE_MULT = 20
STORMCRACK_ATTR_DAMAGE_MULT = 200

HELM_OF_THE_MOUNTAIN_GIANT_PERCENT_HEALTH = 200
HELM_OF_THE_MOUNTAIN_GIANT_PERCENT_DAMAGE_REDUCTION = 50

KNIGHT_HAWK_MAX_MOVESPEED_LIMIT = 300
KNIGHT_HAWK_DR_ABOVE_DEFAULT_MAX = 90
KNIGHT_HAWK_MS_GAIN = 350
KNIGHT_HAWK_MS_BUFF_DURATION = 10

MAGISTRATE_HOOD_MAX_CHARGES = 8
MAGISTRATE_HOOD_REPLENISH_TIME = 1
MAGISTRATE_HOOD_AOE = 300
MAGISTRATE_HOOD_DAMAGE_AMP_PCT = 50