BLACKSMITH_TABLE_ADD_STATS_PCT = 0.65
BLACKSMITH_TABLE_ADD_WEAPON_EXP = 0.4

SAPPHIRE_LOTUS_HP_PER_INT = 25
SAPPHIRE_LOTUS_MP_PER_INT = 5

SAYTARU_HP_THRESHOLD_PCT = 0.5
SAYTARU_PURE_DMG_RESISTANCE = 0.7
SAYTARU_OUTPUT_PURE_AND_MAGIC_DMG_DECREASE = 0.5

STARGAZERS_SPHERE_COOLDOWN = 1.5
STARGAZERS_SPHERE_DURATION = 10
STARGAZERS_SPHERE_DAMAGE_PER_ATT = 20
STARGAZERS_SPHERE_RADIUS = 320
STARGAZERS_SPHERE_METEOR_STUN_DUR = 1
STARGAZERS_SPHERE_STARFALL_DMG_AMP = 1
STARGAZERS_SPHERE_STARFALL_CD = 0.5
STARGAZERS_SPHERE_MAX_PREMIT_DAMAGE_AMP = 10
STARGAZERS_SPHERE_STEADFAST_THRESHOLD = 10
STARGAZERS_SPHERE_MEGASTEADFAST_THRESHOLD = 30

RAZOR_BAND_MAX_HEALTH_DAMAGE = 1
RAZOR_BAND_ATTACK_POWER_PER_STACK = 24
RAZOR_BAND_POST_MITIGATION_PER_STACK = 4
RAZOR_BAND_DAMAGE_PCT_OF_ATTACK_POWER = 10
RAZOR_BAND_MAX_STACKS = 100
RAZOR_BAND_STACK_DURATION = 8

GUARDIAN_STONE_DEBUFF_REDUCTION_PCT = 75
GUARDIAN_STONE_HEAL_PCT = 20

INSPIRATION_MAGIC_IMMUNITY_TIME = 6
INTUITION_ULTIMATE_MIN_CD = 10
