HYDROXIS_Q1_DMG_PCT = 8
HYDROXIS_Q2_ARMOR = 12
HYDROXIS_Q2_HEAL = 200
HYDROXIS_Q3_MAGIC_RESIST = 1.5
HYDROXIS_Q4_MULTI_CAST_PCT = 10
HYDROXIS_Q4_ADD_DMG_PER_ATTR = 30

HYDROXIS_W1_SPLASH_PCT = 5
HYDROXIS_W2_BONUS_ATTACK_DMG_PCT = 4
HYDROXIS_W3_ATTACK_TO_DMG_PCT = 8
HYDROXIS_W4_DMG_PER_MANA_PCT = 0.2
HYDROXIS_W4_MANA_DRAIN_PCT = 3

HYDROXIS_E1_PCT_OF_W = 10
HYDROXIS_E2_ATTACK_TO_DMG_PCT = 10
HYDROXIS_E3_ATTACK_SPEED = 10
HYDROXIS_E4_BONUS_AGI_INT = 350
HYDROXIS_E4_WATER_AMP = 0.1

HYDROXIS_R1_ARMOR_RED = 100
HYDROXIS_R1_BAD_PCT_PER_ARMOR = 0.00002 --0.02% per 10 armor
HYDROXIS_R1_RUNE_MULT = 0.6
HYDROXIS_R2_DMG = 85000
HYDROXIS_R3_ATTACK_TO_DMG_PCT = 35
HYDROXIS_R4_DMG_AMP_PCT = 20
HYDROXIS_R4_DMG_RED_PCT = 1.5

HYDROXIS_ARCANA_W1_SPLASH_PCT = 7.5
HYDROXIS_ARCANA_W2_ATTACK_TO_DMG = 10
HYDROXIS_ARCANA_W3_POST_MITI_PCT = 6
HYDROXIS_ARCANA_W4_MIST_DURATION_BASE = 0.5
HYDROXIS_ARCANA_W4_MIST_DURATION = 0.15
HYDROXIS_ARCANA_W4_BASE_ATTACK = 2500

HYDROXIS_ARCANA_R1_RANGE = 15
HYDROXIS_ARCANA_R1_BAD_PCT = 7.5
HYDROXIS_ARCANA_R2_DURATION_INC = 0.25
HYDROXIS_ARCANA_R3_ROOT_DUR_BASE = 1
HYDROXIS_ARCANA_R3_ROOT_DUR = 0.15
HYDROXIS_ARCANA_R3_WATER_AMP_PCT = 30
HYDROXIS_ARCANA_R4_INT_BONUS = 500
HYDROXIS_ARCANA_R4_POST_MITI_PCT = 10