ASTRAL_Q2_DMG_PER_ATT = 0.36
Q2_PROC_CHANCE = 20
ASTRAL_Q2_STEADFAST_THRESHOLD = 5

W_DELAY = 0.2
W_PARTICLE = "particles/frostivus_herofx/drow_linear_arrow.vpcf"
W_ARROWS_COUNT = 15
W1_ATTRIBUTES_PER_STACK = 1.2
W1_MAX_STACKS_COUNT = 100
ASTRAL_W1_DURATION = 6
W2_MULTIPLY_CHANCE = 10
W3_PARTICLE = "particles/frostivus_gameplay/astral_rune_c_b_linear_frost_arrow.vpcf"
W3_PROC_CHANCE = 20
W3_MULTIPLY_PERCENT = 0.35
W4_DURATION = 4
W4_MAX_STACKS_COUNT = 20

E_PARTICLE1 = "particles/units/heroes/hero_wisp/wisp_relocate_marker_endpoint.vpcf"
E_PARTICLE2 = "particles/units/heroes/hero_dark_seer/dark_seer_surge_start.vpcf"
E_DELAY = 1
E1_START_DURATION = 1
E1_ADD_DURATION = 0.07
E1_MAX_STACKS_COUNT = 10
E1_PARTICLE = "particles/econ/items/mirana/mirana_crescent_arrow/ruins_boss_linear_destruction.vpcf"
E1_RADIUS = 350
E1_SPEED_FROM_RANGE = 7 / 10
E1_TRAVELS_COUNT = 1
ASTRAL_E1_POSTMIT_PCT = 3
E2_PARTICLE = "particles/roshpit/astral_ranger/e2_flash.vpcf"
E2_FIND_RADUIS = 1000
E2_DURATION = 6
E3_START_DURATION = 1
E3_ADD_DURATION = 0.1

ASTRAL_R1_DAMAGE = 10000
ASTRAL_R2_DAMAGE_PCT = 30
ASTRAL_R2_BASE_RADIUS = 50
ASTRAL_R2_RADIUS = 2
ASTRAL_R2_STUN_DURATION = 0.03
ASTRAL_R3_ATTACK_DAMAGE_PERCENT = 1.2
ASTRAL_R3_DURATION = 20
R3_RADIUS = 2500
R4_PROC_CHANCE_INCREASE = 0.01

ARCANA1_Q1_ATTACK_RANGE_INCREASE = 15
ASTRAL_ARCANA1_Q2_DMG_PER_ATT = 0.36
ARCANA1_Q2_PROC_CHANCE = 20
ARCANA1_Q3_DAMAGE_BONUS = 7
ARCANA1_Q4_DAMAGE_PER_ATTRIBUTE = 0.5

ASTRAL_R4_ARCANA2_SLOW = 0.15

WEAPON2_Q2_PROC_CHANCE = 40
WEAPON2_ARCANA1_Q2_PROC_CHANCE = 40

ASTRAL_T11_DURATION = 12
T31_PROC_CHANCE = 40
T31_ARROWS_COUNT = 9
T31_DAMAGE_MULTIPLIER = 2
T41_DELAY = 0.5
ASTRAL_T41_DURATION_REDUCTION_PCT = 25
ASTRAL_T51_CD_REDUCE = 5
T61_TARGETS = 10
T61_DAMAGE_PERCENT = 0.5
T61_ENEMIES_SEARCH_RADIUS = 550

--change E2 to R4 icon
