ZHONIK_Q1_DMG_PCT = 15
ZHONIK_Q2_BASE_DURATION = 6
ZHONIK_Q2_DURATION = 0.1
ZHONIK_Q2_BASE_SEARCH_RADIUS = 200
ZHONIK_Q2_SEARCH_RADIUS = 5
ZHONIK_Q3_POST_MITI_AMP_PCT = 4
ZHONIK_Q4_DMG_TAKEN_REDUCTION_PCT = 0.5
ZHONIK_Q4_DMG_TAKEN_REDUCTION_MAX_PCT = 90

ZHONIK_W1_MUCH_PUNCH_SHOCKWAVE_PCT = 4
ZHONIK_W2_MUCH_PUNCH_AMP_PCT = 1
ZHONIK_W3_DMG_PER_WHIPLASH = 1000
ZHONIK_W4_ECHO_DMG_PCT = 1.2

ZHONIK_E_MANA_DRAIN_PCT = 0.75
ZHONIK_E_MANA_DRAIN = 450
ZHONIK_E1_MS = 6
ZHONIK_E2_DMG_PER_MANA = 20
ZHONIK_E3_PHYS_BLOCK_FLAT = 1
ZHONIK_E4_MS_CAP_INCREASE = 10

ZHONIK_R1_ATTC_DMG_INCR_PCT = 0.5
ZHONIK_R1_EXTRA_STUN_DURATION = 0.01
ZHONIK_R1_BASE_STUN_DURATION = 0.5
ZHONIK_R2_HEALTH_REGEN_PCT = 100
ZHONIK_R2_MANA_REGEN_PCT = 5
ZHONIK_R3_MACH_PUNCH_CHANCE = 10
ZHONIK_R4_BONUS_STR = 350
ZHONIK_R4_ATTC_DMG_PER_STR = 0.3

ZHONIK_E1_ARCANA_ELEMENT_TEMPORAL = 3
ZHONIK_E2_ARCANA_DMG_PCT = 10
ZHONIK_E3_ARCANA_POST_MITI_AMP_PCT = 0.02
ZHONIK_E4_ARCANA_ELEMENT_TEMPORAL_PER_ATRI = 0.06
ZHONIK_E4_ARCANA_MS_STICKY_DURATION = 0.1

ZHONIK_R1_ARCANA_AOE_DMG_PCT = 10
ZHONIK_R2_ARCANA_MUCH_PUNCH_AMP_PCT = 5
ZHONIK_R3_ARCANA_ELEMENT_TEMPORAL = 0.5
ZHONIK_R4_ARCANA_BONUS_AGI = 500
ZHONIK_R4_ATTC_DMG_PER_AGI = 0.5

ZHONIK_GLYPH_1_1_TACHYON_SHELL_RADIUS = 60
ZHONIK_GLYPH_2_1_DAMAGE = 200
ZHONIK_GLYPH_3_1_CHANCE_TO_PUNCH_TWICE = 50
ZHONIK_GLYPH_4_1_SONIC_RADIUS = 100
ZHONIK_GLYPH_5_1_LIGHTSPEED_ADDITIONAL_MS = 200
ZHONIK_GLYPH_6_1_MULTI = 200
ZHONIK_GLYPH_7_1_ELEMENT_TEMPORAL = 75
ZHONIK_GLYPH_5_a_AOE = 8000
