SPIRIT_WARRIOR_Q1_BASE = 220
SPIRIT_WARRIOR_Q1_DMG = 285
spirit_warrior_q3_dmg_pct = 0.1

SPIRIT_WARRIOR_W1_BASE_DMG_PER_MANA = 0.08
SPIRIT_WARRIOR_W2_BASE_DMG = 640

SPIRIT_WARRIOR_E1_DMG = 4400
SPIRIT_WARRIOR_E1_BONUS_WINDSRIKE_PCT = 3
SPIRIT_WARRIOR_E3_DPS = 6000
SPIRIT_WARRIOR_E3_DURATION_BASE = 4
SPIRIT_WARRIOR_E3_DURATION = 0.15

SPIRIT_WARRIOR_R2_BONUS_DMG_PCT = 20

SPIRIT_WARRIOR_W1_ARCANA_BASE_DMG_PER_HP = 0.12
SPIRIT_WARRIOR_W1_ARCANA_BONUS_HP = 2000
SPIRIT_WARRIOR_W2_ARCANA_PCT = 4
spirit_warrior_arcana_w4 = 0.08

SPIRIT_WARRIOR_E1_ARCANA_DMG = 8800
SPIRIT_WARRIOR_E3_ARCANA_DPS = 12000
SPIRIT_WARRIOR_E3_ARCANA_DURATION_BASE = 3
SPIRIT_WARRIOR_E3_ARCANA_DURATION = 0.12

SPIRIT_WARRIOR_ARCANA_R2_RADIUS = 200
SPIRIT_WARRIOR_ARCANA_R3_POST_MITI_PCT = 3

spirit_warrior_glyph_7_1_additional_duration = 40
