CONJUROR_W1_ARCANA_ATTACK_PCT_FROM_INT = 0.03
CONJUROR_W1_BASE_ATTACK_FROM_BUFF = 10000

CONJUROR_ARCANA_W2_FLAT_FIRE_AMP = 50
CONJUROR_ARCANA_W2_DAMAGE_BONUS_W_PCT = 100

CONJUROR_ARCANA_W3_CRIT_DMG_PCT = 60

CONJUROR_ARCANA_W4_AGI_AND_INT_PCT = 2
CONJUROR_ARCANA_W4_STR_PCT = -1

CONJUROR_ARCANA_Q1_DMG_PERCENT_MAX_HEALTH = 60
CONJUROR_ARCANA_Q1_RADIUS_BASE = 500
CONJUROR_ARCANA_Q1_RADIUS_SCALE = 5

CONJUROR_ARCANA_Q2_FLAT_HEALTH = 1800
CONJUROR_ARCANA_Q2_PERCENT_HEALTH = 4

CONJUROR_ARCANA_Q3_EARTH_AMP_FOR_100_MAX_HEALTH = 0.01
CONJUROR_ARCANA_Q3_ATTACK_DMG_TO_EARTH_SHOCK_PCT = 100

CONJUROR_ARCANA_Q4_DAMAGE_REDUCE_PCT = 1.2

CONJUROR_ARCANA_E1_ATTACK_POWER_BLACK_RAZOR = 15
CONJUROR_ARCANA_E1_ATTACK_POWER_BONUS_PCT = 10

CONJUROR_ARCANA_E2_SHADOW_DAMAGE_INSTANCES = 2

CONJUROR_ARCANA_E3_SHADOW_AMP = 0.01
CONJUROR_ARCANA_E3_AGILITY_GEAR_AMP = 2

CONJUROR_ARCANA_E4_SPLIT_CHANCE = 10

--BASIC
CONJUROR_W1_DMG_BASE = 600
CONJUROR_W1_DMG = 2510
CONJUROR_W1_HEALTH_GAIN_PCT = 0.12
CONJUROR_W2_BONUS_DMG_PCT = 10
CONJUROR_W3_CRIT_DMG_PCT = 45
CONJUROR_W4_HEALTH_DAMAGE_PER_TICK = 100
CONJUROR_W4_AMP_ON_FIRE = 150

CONJUROR_E1_BONUS_DMG_PCT = 1

CONJUROR_R2_BONUS_DMG_PCT = 20