DINATH_Q1_MOVESPEED_SLOW = 5
DINATH_Q2_FIRE_DURATION = 0.08
DINATH_Q3_CAST_RANGE_BASE = 500
DINATH_Q3_CAST_RANGE = 12
DINATH_Q4_CAST_RATE_REDUCTION = 1.5

DINATH_W1_BONUS_ATTACK_DAMAGE = 0.06
DINATH_W2_POST_MITI_MAGIC = 0.1
DINATH_W3_ROOT_BASE = 0.3
DINATH_W3_ROOT = 0.1
DINATH_W4_RADUIS = 4

DINATH_E1_ATTACK_SPEED = 12
DINATH_E2_GEAR_BASE_DAMAGE_AMP = 0.15
DINATH_E3_ATTACK_RANGE = 15
DINATH_E4_Z_THRESHOLD_BASE = 450
DINATH_E4_Z_THRESHOLD_REDUCTION = 3

DINATH_R1_ATTACK_TO_DAMAGE = 0.05
DINATH_R2_POST_MITI = 0.09
DINATH_R3_CHARGE_RATE = 0.01
DINATH_R4_DRAGON_AMP = 0.0015

DINATH_ARCANA_W1_BONUS_ATTACK_DAMAGE  = 0.08
DINATH_ARCANA_W2_MOVESPEED_TO_ICE_AMP_DIV_BY_100 = 0.001
DINATH_ARCANA_W3_MOVESPEED_BONUS = 8
DINATH_ARCANA_W3_MOVESPEED_CAP_BONUS = 5
DINATH_ARCANA_W4_ATTACK_RADIUS_INCREASE = 8
DINATH_ARCANA_W4_CHANCE_FOR_TARGET = 10