SEPHYR_Q1_INT_BONUS = 125
SEPHYR_Q2_POSTMIT = 0.1
SEPHYR_Q3_STACKS = 1
SEPHYR_Q3_HOLY_AMP_PCT = 10
SEPHYR_Q4_HOLY_AMP_PCT = 100
SEPHYR_Q4_HOLY_TO_ATT_BONUS_PCT = 0.5

SEPHYR_W1_INT_TO_MANA_REGEN_PCT = 2.5
SEPHYR_W2_CRIT_BONUS_PCT = 20
SEPHYR_W3_ATTACK_TO_DAMAGE_PCT = 2
SEPHYR_W4_WIND_AMP_PCT = 0.12

SEPHYR_E1_BOUNCE_CHANCE = 10
SEPHYR_E1_DAMAGE = 1500
SEPHYR_E2_BONUS_ATTACK_DAMAGE = 800
SEPHYR_E2_ATTACK_TO_DAMAGE_PCT = 15
SEPHYR_E3_BASE_ATTACK_DAMAGE_PER_AGI = 0.2
SEPHYR_E3_BONUS_PUCK_DAMAGE_PER_AGI = 1.5
SEPHYR_E4_STRAFE_SPEED = 0.15
SEPHYR_E4_STRAFE_DISTANCE = 6


SEPHYR_R1_HP_REGEN_PER_LVL = 20
SEPHYR_R2_ATT_SPEED_SLOW = -8
SEPHYR_R2_MS_SPEED_SLOW = -10
SEPHYR_R3_MOVESPEED = 10
SEPHYR_R3_STRAFE_SPEED = 0.12
SEPHYR_R4_BONUS_INT = 500
SEPHYR_R4_BONUS_AGI = 500

SEPHYR_ARCANA_W1_MANA_REGEN_FLAT = 35
SEPHYR_ARCANA_W1_DAMAGE_PER_MANAREGEN = 0.3
SEPHYR_ARCANA_W2_ATTACK_TO_DAMAGE_PCT = 4
SEPHYR_ARCANA_W3_SHIELD_CHANCE = 4
SEPHYR_ARCANA_W4_WIND_AMP_PCT = 0.15

SEPHYR_ARCANA_GALE_RANGE = 800
SEPHYR_ARCANA_GALE_SPEED = 2500
SEPHYR_ARCANA_GALE_RANGE_GLYPH41 = 1200
SEPHYR_ARCANA_GALE_SPEED_GLYPH41 = 3500
SEPHYR_ARCANA_GALE_CRIT_CHANCE = 15