DJANGHOR_Q1_REGEN_FLAT = 80
DJANGHOR_Q1_REGEN_PCT = 0.05
DJANGHOR_Q2_ATT = 20000
DJANGHOR_Q2_SELF_MULTIPLE = 10
DJANGHOR_Q3_BUFF_DURATION_INCREASE = 0.2

DJANGHOR_W1_DAMAGE_MULT = 0.15
DJANGHOR_W2_POST_MIT_PCT = 8
DJANGHOR_W3_ATTACK_PERCENT_ADDED_TO_TORNADO_AND_STOMP = 0.2

DJANGHOR_E2_JINBO_BOOST_IN_LEAP = 0.25
DJANGHOR_E4_DURATION_INCREASE = 0.15

DJANGHOR_R1_ATTACK_POWER_PER_STAT = 0.3
DJANGHOR_R3_BEAR_ITEM_DAMAGE_PCT = 0.12

DJANGHOR_GLYPH_4_1_SHIELD_STACKS = 7

DJANGHOR_R1_ARCANA_ATTACK_POWER = 0.2
DJANGHOR_R2_ARCANA_HEALTH_PER_ATTRIBUTE = 0.1
DJANGHOR_R3_ARCANA_RESIST_PCT = 0.01
DJANGHOR_R3_ARCANA_RESIST_MAX_PCT = 0.9

DJANGHOR_WEAP_2_HP_THRESHOLD_PCT = 0.08
