--ELEMENTS--
RPC_ELEMENT_COUNT = 18

RPC_ELEMENT_NONE = -1
RPC_ELEMENT_NORMAL = 1
RPC_ELEMENT_FIRE = 2
RPC_ELEMENT_EARTH = 3
RPC_ELEMENT_LIGHTNING = 4
RPC_ELEMENT_POISON = 5
RPC_ELEMENT_TIME = 6
RPC_ELEMENT_HOLY = 7
RPC_ELEMENT_COSMOS = 8
RPC_ELEMENT_ICE = 9
RPC_ELEMENT_ARCANE = 10
RPC_ELEMENT_SHADOW = 11
RPC_ELEMENT_WIND = 12
RPC_ELEMENT_GHOST = 13
RPC_ELEMENT_WATER = 14
RPC_ELEMENT_DEMON = 15
RPC_ELEMENT_NATURE = 16
RPC_ELEMENT_UNDEAD = 17
RPC_ELEMENT_DRAGON = 18

RPC_ELEMENT_NORMAL_COLOR = "#DDDDDD"
RPC_ELEMENT_FIRE_COLOR = "#EF4126"
RPC_ELEMENT_EARTH_COLOR = "#AF843D"
RPC_ELEMENT_LIGHTNING_COLOR = "#5CCDF9"
RPC_ELEMENT_POISON_COLOR = "#37DD3D"
RPC_ELEMENT_TIME_COLOR = "#B5FFB7"
RPC_ELEMENT_HOLY_COLOR = "#F6FFB5"
RPC_ELEMENT_COSMOS_COLOR = "#C25DFC"
RPC_ELEMENT_ICE_COLOR = "#87D9FF"
RPC_ELEMENT_ARCANE_COLOR = "#E1A2E8"
RPC_ELEMENT_SHADOW_COLOR = "#7F4F84"
RPC_ELEMENT_WIND_COLOR = "#7AE2A7"
RPC_ELEMENT_GHOST_COLOR = "#9ACCD1"
RPC_ELEMENT_WATER_COLOR = "#3894FF"
RPC_ELEMENT_DEMON_COLOR = "#5B648C"
RPC_ELEMENT_NATURE_COLOR = "#69BC71"
RPC_ELEMENT_UNDEAD_COLOR = "#5C776E"
RPC_ELEMENT_DRAGON_COLOR = "#3289C7"

--SKILL SLOTS--
DOTA_Q_SLOT = 0
DOTA_W_SLOT = 1
DOTA_E_SLOT = 2
DOTA_D_SLOT = 3
DOTA_F_SLOT = 4
DOTA_R_SLOT = 5

--BASE--
BASE_NONE = -1
BASE_ITEM = 0
BASE_ABILITY_Q = 1
BASE_ABILITY_W = 2
BASE_ABILITY_E = 3
BASE_ABILITY_R = 4
BASE_AUTO_ATTACK = 5

--ENEMY TYPE--
ENEMY_TYPE_WEAK_CREEP = 0
ENEMY_TYPE_NORMAL_CREEP = 1
ENEMY_TYPE_MINI_BOSS = 2
ENEMY_TYPE_BOSS = 3
ENEMY_TYPE_MAJOR_BOSS = 4

--DIFFICULTY--
DIFFICULTY_NORMAL = 1
DIFFICULTY_ELITE = 2
DIFFICULTY_LEGEND = 3

NPC_LUA_UNIT = 'lua_unit'

--Modifier special types--

-- DAMAGE --
MODIFIER_SPECIAL_TYPE_ABILITIES = 1
MODIFIER_SPECIAL_TYPE_ITEMS = 2
MODIFIER_SPECIAL_TYPE_ELEMENTS = 3 -- added to current calculation
MODIFIER_SPECIAL_TYPE_STEADFAST = 4
MODIFIER_SPECIAL_TYPE_POSTMITIGATION = 5 -- added to current calculation
MODIFIER_SPECIAL_TYPE_EXTRA_POSTMITIGATION = 6 -- added to current calculation
MODIFIER_SPECIAL_TYPE_PREMITIGATION = 7
MODIFIER_SPECIAL_TYPE_LETHAL_CHECK = 8
MODIFIER_SPECIAL_TYPE_LETHAL = 9 -- added to current calculation
MODIFIER_SPECIAL_TYPE_AUGMENTED = 10
MODIFIER_SPECIAL_TYPE_DOT = 11

-- Other --
MODIFIER_SPECIAL_TYPE_ORDER_FILTER = 12
MODIFIER_SPECIAL_TYPE_CAST_Q_ABILITY = 13
MODIFIER_SPECIAL_TYPE_CAST_W_ABILITY = 14
MODIFIER_SPECIAL_TYPE_CAST_E_ABILITY = 15
MODIFIER_SPECIAL_TYPE_CAST_R_ABILITY = 16