FLAMEWAKER_Q4_BASE_DMG_PER_HP = 0.05
FLAMEWAKER_Q4_BASE_DMG_PER_DAMAGE = 0.001

FLAMEWAKER_W1_DMG_PER_ATT = 0.1
FLAMEWAKER_W3_ARMOR_SHRED = -12
FLAMEWAKER_W4_BONUS_DMG_PCT = 50

FLAMEWAKER_E1_DMG = 600
FLAMEWAKER_E1_PREMIT = 0.001
FLAMEWAKER_E3_BONUS_DMG_PCT = 10
FLAMEWAKER_E3_ATT_SPEED = 12

FLAMEWAKER_R1_BONUS_ATT_DMG_PCT = 25
FLAMEWAKER_R2_INNER_SCALE_BASE = 0.1
FLAMEWAKER_R2_DMG_EXP_SCALE_BASE = 4
FLAMEWAKER_R2_SCALE = 0.5
FLAMEWAKER_R2_INSTANCE_OF_DAMAGE_COUNT = 7

FLAMEWAKER_ARCANA_Q_COOLDOWN = 3 -- for prevent interaction with minus cd items in future
FLAMEWAKER_ARCANA_Q_FREE_CAST_DURATION = 0.5
FLAMEWAKER_ARCANA_Q_RADIUS = 360
FLAMEWAKER_ARCANA_Q_MIN_DISTANCE = 200
FLAMEWAKER_ARCANA_Q_MAX_DISTANCE = 1200
FLAMEWAKER_ARCANA_Q1_ARMOR_PER_STACK = 0.4
FLAMEWAKER_ARCANA_Q1_MANAREGEN_PER_STACK = 2
FLAMEWAKER_ARCANA_Q1_MISSED_HP_FOR_GET_STACK_BASE = 200
FLAMEWAKER_ARCANA_Q1_MAX_STACKS_BASE = 500
FLAMEWAKER_ARCANA_Q2_DURATION = 6
FLAMEWAKER_ARCANA_Q3_PROC_CHANCE = 10
FLAMEWAKER_ARCANA_Q3_DELAY = 0.2
FLAMEWAKER_ARCANA_Q4_DMG_PER_ATT = 2

FLAMEWAKER_T51_R2_DUR_MULTIPLY = 1.5

